Updated usercode API
futurehomeno/fimp-api pull request #34
Opened 2020-10-26 09:20 UTC by imilicevic7

Changes approved by Diaa.
+
Fixed annoying Z-Wave misspelling.

2020-10-27 09:22 UTC, ditek requested changes

2020-10-27 09:22 UTC, ditek commented on README.md
> -`sup_usercodes`  | ["pin", "rfid"]            | List of supported user code types
I believe we should keep those. I checked zigbee-ad and it uses `code_type` (pin/rfid), `user_status` (enabled/disabled) and `user_type` (master/unrestricted). I think that's where those came from.

2020-10-27 09:22 UTC, ditek commented on README.md
> +in   | cmd.usercode.set               | str_map    |
Could you add what fields in the string map are expected?

2020-10-27 09:22 UTC, ditek commented on README.md
> +in   | cmd.usercode.get               | null       | Will return all slots for all medium
Could you add how the get response looks like?

2020-10-27 09:22 UTC, ditek commented on README.md
>  out  | evt.usercode.access_report     | str_map    |
It's not clear when this message is sent or what it contains

2020-11-05 07:18 UTC, bjhandeland commented
@imilicevic7 can you please update based on review?

2020-12-09 09:52 UTC, bjhandeland commented
@imilicevic7 bump

2022-06-28 10:09 UTC, bjhandeland commented
@eternalamenity Can you check if this is still valid? If no, close the PR.

2022-07-22 11:45 UTC, BudzikM commented
Good afternoon. Is the owner of this PR still alive ?

2022-07-22 11:47 UTC, bjhandeland commented
Unlikely. @BudzikM closing the PR.

2022-07-22 11:47 UTC, closed without merging