Boiler services: water_heater and sensor_water_temp
futurehomeno/fimp-api pull request #39
Opened 2022-01-11 10:21 UTC by boguslaw-wojcik

2022-02-07 10:53 UTC, bjhandeland requested changes
nits

2022-02-09 11:45 UTC, bjhandeland approved these changes
lgtm

2022-02-17 18:03 UTC, chribru submitted a review, later dismissed
changes look good, but please make sure that commit messages reflect the contents of the commits

2022-02-18 10:31 UTC, chribru approved these changes
lgtm

2022-02-18 10:32 UTC, merged