SDU-2349: Added supported temperatures to setpoints
futurehomeno/fimp-api pull request #81
Opened 2022-11-03 13:01 UTC by PaulinaDrozda

2022-11-07 17:20 UTC, eternalamenity approved these changes

2022-11-07 21:07 UTC, boguslaw-wojcik requested changes
Please include object specification in the definitions section if you introduce new objects or enums that cannot be explained briefly in description section.

Use sup_ranges from water_heater service from this link as reference:

 https://github.com/futurehomeno/fimp-api/blob/master/services/generic/water_heater.md#service-properties
 
 Also consider whether you want different structure than what is already in water_heater.

2022-11-08 10:17 UTC, boguslaw-wojcik approved these changes

2022-11-08 10:33 UTC, merged

2022-11-09 10:13 UTC, eternalamenity commented on services/generic/thermostat.md
> +* `range` is an object with the following structure:
@boguslaw-wojcik do we want to call those "object" with a temporary name that is not used actually in value?