SDU-3087: Added Sound Switch service
futurehomeno/fimp-api pull request #86
Opened 2022-12-28 07:30 UTC by PaulinaDrozda

2023-01-02 07:49 UTC, boguslaw-wojcik commented on services/generic/sound_switch.md
> +| `sup_tones` | object | List of supported tones. Contains `tone_id`, `duration` (in seconds) and the `name` of the tone. See Examples.                |
Create object definition for a supported tone.

2023-01-02 07:51 UTC, boguslaw-wojcik requested changes
Small style/formatting/documenting issues.

2023-01-02 12:06 UTC, boguslaw-wojcik commented on services/services.md
> +- [Sound switch](/services/generic/sound_switch.md)
Add it also to _sidebar.md.

2023-01-02 14:02 UTC, boguslaw-wojcik commented on services/services.md
> +- [Sound switch](/services/generic/sound_switch.md)
@PaulinaDrozda This way it will be visible as well when navigating using live documentation.

2023-01-03 09:15 UTC, BudzikM commented on services/generic/sound_switch.md
> +Sound Switch service allows you to control the sound tones on the device.
..allows to control..
..on the remote device...

2023-01-03 09:15 UTC, BudzikM commented on services/generic/sound_switch.md
> +| in   | cmd.config.get_report | null       | Request the current configuration of the device.                                      |
Requests

2023-01-03 09:16 UTC, BudzikM commented on services/generic/sound_switch.md
> +| in   | cmd.play.set          | int_map    | Control device to play a specific tone, see [`play_map`](#definitions) for more info. |
Controls

2023-01-03 09:16 UTC, BudzikM commented on services/generic/sound_switch.md
> +* `play_map` is an int_map with the following structure:
of the following...

2023-01-03 09:22 UTC, Brzezoo submitted a review, later dismissed

2023-01-03 10:46 UTC, boguslaw-wojcik approved these changes
Just do the nitpicks from Budzik

2023-01-04 07:24 UTC, boguslaw-wojcik approved these changes

2023-01-10 14:36 UTC, eternalamenity approved these changes
lgtm

2023-01-13 08:53 UTC, merged